"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type ContextRow = { campaign_id: string; generation_context_id: string; run_id: string; created_at: string; context_item_count: number; payload_count: number };

export default function HomePage() {
  const router = useRouter(); const [rows, setRows] = useState<ContextRow[]>([]); const [campaign, setCampaign] = useState(""); const [context, setContext] = useState(""); const [run, setRun] = useState(""); const [selected, setSelected] = useState<any>(null);
  async function load() { const query = new URLSearchParams({ ...(campaign && { campaign_id: campaign }), ...(context && { generation_context_id: context }), ...(run && { run_id: run }), limit: "100" }); const response = await fetch(`/api/contexts?${query}`); if (response.status === 401) return router.push("/login"); setRows(await response.json()); }
  useEffect(() => { load(); }, []);
  async function detail(id: string) { const response = await fetch(`/api/contexts/${encodeURIComponent(id)}`); if (response.status === 401) return router.push("/login"); setSelected(await response.json()); }
  function download() { const blob = new Blob([JSON.stringify(selected, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${selected.generation_context_id}.json`; link.click(); URL.revokeObjectURL(link.href); }
  return <main style={{ maxWidth: 1250, margin: "0 auto", padding: 32 }}><header style={{ display: "flex", justifyContent: "space-between" }}><div><p style={{ color: "#5d6b7a" }}>ADMINISTRATOR TOOL</p><h1>LLM Context Viewer</h1></div><button onClick={async () => { await fetch("/api/logout", { method: "POST" }); router.push("/login"); }}>Sign out</button></header><section style={{ background: "white", padding: 20, borderRadius: 12, display: "flex", gap: 10, flexWrap: "wrap" }}><input placeholder="Campaign ID" value={campaign} onChange={e => setCampaign(e.target.value)} /><input placeholder="Generation context ID" value={context} onChange={e => setContext(e.target.value)} /><input placeholder="Run ID" value={run} onChange={e => setRun(e.target.value)} /><button onClick={load}>Search</button></section><div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1.4fr)", gap: 20, marginTop: 20 }}><section style={{ background: "white", borderRadius: 12, overflow: "auto" }}><table style={{ width: "100%", textAlign: "left" }}><thead><tr><th>Campaign</th><th>Generation context</th><th>Run</th><th>Payloads</th></tr></thead><tbody>{rows.map(row => <tr key={row.generation_context_id} onClick={() => detail(row.generation_context_id)} style={{ cursor: "pointer" }}><td>{row.campaign_id}</td><td>{row.generation_context_id}</td><td>{row.run_id}</td><td>{row.payload_count}</td></tr>)}</tbody></table></section><section style={{ background: "#111923", color: "#d9e2ec", borderRadius: 12, padding: 20, minHeight: 400, overflow: "auto" }}>{selected ? <><button onClick={() => navigator.clipboard.writeText(JSON.stringify(selected, null, 2))}>Copy JSON</button> <button onClick={download}>Download JSON</button><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{JSON.stringify(selected, null, 2)}</pre></> : <p>Select a generation context to inspect its prompt and context.</p>}</section></div></main>;
}
